version: '3'

services:
  wordpress:
    image: wordpress:latest
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: example_user
      WORDPRESS_DB_PASSWORD: example_password
      WORDPRESS_DB_NAME: example_database
    volumes:
      - ./wp-content:/var/www/html/wp-content
    ports:
      - 8080:80
  db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example_root_password
      MYSQL_DATABASE: example_database
      MYSQL_USER: example_user
      MYSQL_PASSWORD: example_password
  nginx:
    image: nginx:latest
    depends_on:
      - wordpress
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - ./nginx-conf:/etc/nginx/conf.d
    ports:
      - 80:80